name: Run Benchmarks
on:
  workflow_dispatch:

jobs:
  run-benchmarks:
    name: Run Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - windows-latest
          - windows-11-arm
          - ubuntu-22.04
          - ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Measure performance
        run: |
          rm -r results
          npm install
          npm test

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: results
